title: Trevor Maxwell # your name (or website title) here
logo: "/images/Portrait_outside.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Detective Translating Data To Insightful Stories    <br><br>
  ### About
  I have had the opportunity for many years to work with teams to solve problems. 
  I enjoy environments with teamwork and challenges to overcome. I feel tech is the place 
  to be as we move towards integration with AI more and more. <br>
  Skills;
  - SQL
  - Tableau
  - PowerBI
  - Excel
  - Python 
  <br><br>
  <a href="https://www.linkedin.com/in/trevor2maxwell/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
