title: Trevor Maxwell # your name (or website title) here
logo: "/images/Portrait_outside.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Translating Data To Insightful Stories    <br><br>
  <a href="https://www.linkedin.com/in/trevor2maxwell/">View My LinkedIn Profile</a> 

  additional_text: |
    I am currently seeking a challenging position in data analytics
    to make the most of my technical domain expertise and analytical skills. 
    I enjoy the collaboration and growth that comes with the tech industry.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
