title: Trevor Maxwell # your name (or website title) here
logo: "/images/Portrait_outside.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Translating Data To Insightful Stories    <br><br>
  <a href="https://www.linkedin.com/in/trevor2maxwell/">View My LinkedIn Profile</a> <br>

   The advancement of AI piqued my interest. What started as an exploration of the emerging technology 
   turned into a career transition. I am excited to be working as a technical business analyst. I am 
   looking forward to what I will continue to learn and discover.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
